### ISSUE TITLE
The engine "node" is incompatible with this module. Expected version  "^12.14.0". Got "12.13.1"

### ISSUE THREAD

**Issue by dulara1994** [LeafyCode/survive-together-web#3]
![WhatsApp Image 2020-04-04 at 10 10 14 AM](https://user-images.githubusercontent.com/26034746/78419006-fe14c980-765e-11ea-91e2-a5fc9ffc6b2b.jpeg)

I encountered with the above-mentioned error while running yarn install.

I had to change the node version to run this app.
why this package  react-youtube@7.10.0 require that much higher node version?

**Comment by THPubs** [comment]
Ah that's because of the `react-embed` plugin I used to embed imgur images. Since we are not advising people to use that service anymore we can safely remove it. I just removed and updated the repo. Can you please pull it and see whether you face the same issue with an older node version?

**Comment by dulara1994** [comment]
![image](https://user-images.githubusercontent.com/26034746/78451531-c1b78c80-76a3-11ea-8183-005e1256b96c.png)
It is working fine now. thank you!
